from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin_profile/', views.admin_profile, name='admin_profile'),
    path('edit_admin_profile/', views.edit_admin_profile, name='edit_admin_profile'),
    path('change_admin_password/', views.change_admin_password, name='change_admin_password'),
    path('add_category/', views.add_category, name='add_category'),
    path('delete_category/<int:id>/', views.delete_category, name='delete_category'),
    path('add_product/', views.add_product, name='add_product'),
    path('view_products/', views.view_products, name='view_products'),
    path('edit_product/<int:id>/', views.edit_product, name='edit_product'),
    path('delete_product/<int:id>/', views.delete_product, name='delete_product'),
    path('view_users/', views.view_users, name='view_users'),
    path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
    path('add_cart/', views.add_cart, name='add_cart'),
    path('add-to-cart/<int:id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_page, name='cart'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('delete_cart/<int:id>/', views.delete_cart, name='delete_cart'),
    path('payment/<int:id>/', views.payment_page, name='payment_page'),
    path('payment/', views.payment, name='payment'),
    path('buy_single/<int:cart_id>/', views.buy_single, name='buy_single'),
    path('buy_all/', views.buy_all, name='buy_all'),
    path('place_order/', views.place_order, name='place_order'),
    path('search/', views.search_cake, name='search_cake'),
    path('flavour/<int:id>/', views.flavour_cakes, name='flavour_cakes'),
    path('view_profile/', views.view_profile, name='view_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_user_password, name='change_password'),
    path('cart_count/', views.cart_count_api, name='cart_count_api'),
    path('check_user_exists/', views.check_user_exists, name='check_user_exists'),
    path('check_current_password/', views.check_current_password, name='check_current_password'),
    path('delete_user/<int:id>/', views.delete_user, name='delete_user'),
]